"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

def solution():
    nums_to_solve = 2000
    min_dif = 1_000_000_000
    pent_nums = [n * (3 * n - 1) //2 for n in range(nums_to_solve)]
    for i in range(nums_to_solve - 1):
        for j in range(i, nums_to_solve):
            sum_pents = pent_nums[i] + pent_nums[j]
            diff_pents = abs(pent_nums[i] - pent_nums[j])
            if sum_pents in pent_nums and diff_pents in pent_nums:
                min_dif = min(min_dif, diff_pents)
    return min_dif

print(solution())